<?php
require_once('functions/default.php');
require_once('functions/theme.php');
require_once('functions/enqueue.php');
require_once('functions/post-types.php');
require_once('functions/media.php');
require_once('functions/breadcrumbs.php');
require_once('functions/pagination.php');
require_once('functions/acf-blocks.php');
require_once('functions/ajax-filters.php');